### ISSUE TITLE
DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead

### ISSUE THREAD

**Issue by hkansal27** [chrisbateman/webpack-visualizer#55]
Hi,

This warning is causing, due to upgradation on Webpack 4 because they are still using the old plugin API, they need to be upgraded to the latest version.

I am getting the below error:

(node:10740) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
[ERROR]     at VisualizerPlugin.apply (C:\Users\Hp\Desktop\New folder (2)\gateway_upgrade\node_modules\webpack-visualizer-plugin\lib\plugin.js:44:22)
[ERROR]     at webpack (C:\Users\Hp\Desktop\New folder (2)\gateway_upgrade\node_modules\webpack\lib\webpack.js:37:12)
[ERROR]     at processOptions (C:\Users\Hp\Desktop\New folder (2)\gateway_upgrade\node_modules\webpack-cli\bin\webpack.js:437:16)
[ERROR]     at yargs.parse (C:\Users\Hp\Desktop\New folder (2)\gateway_upgrade\node_modules\webpack-cli\bin\webpack.js:513:3)
[ERROR]     at Object.parse (C:\Users\Hp\Desktop\New folder (2)\gateway_upgrade\node_modules\webpack-cli\node_modules\yargs\yargs.js:552:18)
[ERROR]     at C:\Users\Hp\Desktop\New folder (2)\gateway_upgrade\node_modules\webpack-cli\bin\webpack.js:218:8
[ERROR]     at Object.<anonymous> (C:\Users\Hp\Desktop\New folder (2)\gateway_upgrade\node_modules\webpack-cli\bin\webpack.js:515:3)
[ERROR]     at Module._compile (module.js:652:30)
[ERROR]     at Object.Module._extensions..js (module.js:663:10)
[ERROR]     at Module.load (module.js:565:32)
[ERROR]     at tryModuleLoad (module.js:505:12)
[ERROR]     at Function.Module._load (module.js:497:3)
[ERROR]     at Module.require (module.js:596:17)
[ERROR]     at require (internal/module.js:11:18)
[ERROR]     at Object.<anonymous> (C:\Users\Hp\Desktop\New folder (2)\gateway_upgrade\node_modules\webpack\bin\webpack.js:80:2)
[ERROR]     at Module._compile (module.js:652:30)
[ERROR]     at Object.Module._extensions..js (module.js:663:10)
[ERROR]     at Module.load (module.js:565:32)
[ERROR]     at tryModuleLoad (module.js:505:12)
[ERROR]     at Function.Module._load (module.js:497:3)
[ERROR]     at Function.Module.runMain (module.js:693:10)
[ERROR]     at startup (bootstrap_node.js:191:16)
[ERROR]     at bootstrap_node.js:612:3

**Comment by jacksonmj24** [comment]
Any update on this ??

**Comment by samsan1212** [comment]
any update?

**Comment by jaclas** [comment]
update?

**Comment by opalampo** [comment]
@chrisbateman Why are there no updates on this? It has been months that it has been an issue...

**Comment by duxy2002** [comment]
update?

**Comment by mabliedana** [comment]
This workaround has worked for me

File: node_modules/webpack-visualizer-plugin/lib/plugin.js
Line: 44

change
`compiler.plugin('emit', function (compilation, callback) {
`
by
`compiler.hooks.done.tap('emit', function (compilation, callback) {
`

**Comment by AzadRazvi** [comment]
I am getting this issue when upgrading from Webpack3 to Webpack4
error details
DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
    at VisualizerPlugin.apply (node_modules\webpack-visualizer-plugin\lib\plugin.js:44:22)
    at webpack (node_modules\webpack\lib\webpack.js:47:13)
Can any one let me know which version of webpack i need to use after 4 and i will not modify in node modules.
