### ISSUE TITLE
DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead at VisualizerPlugin.apply

### ISSUE THREAD

**Issue by AzadRazvi** [chrisbateman/webpack-visualizer#64]
i am doing SPFx upgrade to 1.9.1 and also i am doing Webpack upgrade to 4. Please help me to resolve the warning for mentioned error.
DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead

**Comment by a-mi-go** [comment]
Same issue after updating to webpack 4:

`DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
    at VisualizerPlugin.apply (/xxx/node_modules/webpack-visualizer-plugin/lib/plugin.js:44:22)
    at webpack (/xxx/node_modules/webpack/lib/webpack.js:51:13)
    at processOptions (/xxx/node_modules/webpack-cli/bin/cli.js:272:16)
    at /xxx/node_modules/webpack-cli/bin/cli.js:364:3
    at Object.parse (/xxx/node_modules/webpack-cli/node_modules/yargs/yargs.js:567:18)
    at /xxx/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/xxx/node_modules/webpack-cli/bin/cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/xxx/node_modules/webpack/bin/webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11`

Using:
    "webpack": "4.41.2",
    "webpack-cli": "3.3.10",
    "webpack-dev-server": "3.9.0",
    "webpack-merge": "4.2.2",
    "webpack-notifier": "1.8.0",
    "webpack-visualizer-plugin": "0.1.11",
    "workbox-webpack-plugin": "4.3.1",
    "write-file-webpack-plugin": "4.5.1",

**Comment by jonamat** [comment]
This package is no longer maintained. If you need it I forked this package to use it with webpack 4 and 5 hooks. 
Use `npm i -D webpack-visualizer-plugin2`
